name: Deploy Medusa Store to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t mohdshoaib84/medusa-store:latest .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push mohdshoaib84/medusa-store:latest

      # Step 6: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 7: Register new ECS task definition
      - name: Register new ECS task definition
        id: register-task-def
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://ecs-task-def.json > task-def-result.json
          echo "task_definition_arn=$(jq -r '.taskDefinition.taskDefinitionArn' task-def-result.json)" >> $GITHUB_OUTPUT

      # Step 8: Update ECS service
      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster medusa-task \
            --service medusa-service \
            --task-definition ${{ steps.register-task-def.outputs.task_definition_arn }} \
            --force-new-deployment \
            --region us-east-1

      # Step 9: Wait for ECS service to stabilize
      - name: Wait for ECS service to stabilize
        run: |
          aws ecs wait services-stable \
            --cluster medusa-task \
            --services medusa-service \
            --region us-east-1
          echo "ECS service is now stable"
